name: Yunchef Lunch Scheduler

on:
  schedule:
    - cron: '17 3 * * 1-5'
  workflow_dispatch:

jobs:
  call-apps-script:
    runs-on: ubuntu-latest
    steps:
      - name: Call Apps Script
        run: |
          curl -L "${{ secrets.YUNCHEF_URL }}"
